// GENERATED from assets/service_picture — do not edit by hand.
abstract final class MarketingServiceAssetPaths {
  static const byCategoryAndName = <String, String>{
    'home_repair|basic carpentry': r'assets/service_picture/1. Home Repair/Basic Carpentry.jpg',
    'home_repair|cabinet repair': r'assets/service_picture/1. Home Repair/Cabinet Repair.jpg',
    'home_repair|ceiling repair': r'assets/service_picture/1. Home Repair/Ceiling Repair.jpg',
    'home_repair|door repair': r'assets/service_picture/1. Home Repair/Door Repair.jpg',
    'home_repair|faucet replacement': r'assets/service_picture/1. Home Repair/Faucet Replacement.jpg',
    'home_repair|fence repair': r'assets/service_picture/1. Home Repair/Fence Repair.jpg',
    'home_repair|flooring repair': r'assets/service_picture/1. Home Repair/Flooring Repair.jpg',
    'home_repair|gate repair': r'assets/service_picture/1. Home Repair/Gate Repair.jpg',
    'home_repair|home maintenance': r'assets/service_picture/1. Home Repair/Home Maintenance.jpg',
    'home_repair|home repair': r'assets/service_picture/1. Home Repair/Home Repair.jpg',
    'home_repair|lock repair': r'assets/service_picture/1. Home Repair/Lock Repair.jpg',
    'home_repair|minor renovation help': r'assets/service_picture/1. Home Repair/Minor Renovation Help.jpg',
    'home_repair|roof leak repair': r'assets/service_picture/1. Home Repair/Roof Leak Repair.jpg',
    'home_repair|tile repair': r'assets/service_picture/1. Home Repair/Tile Repair.jpg',
    'home_repair|wall repair': r'assets/service_picture/1. Home Repair/Wall Repair.jpg',
    'home_repair|window repair': r'assets/service_picture/1. Home Repair/Window Repair.jpg',
    'community|backyard cleaning': r'assets/service_picture/10. More  Community Help/Backyard Cleaning.jpg',
    'community|bag cleaning': r'assets/service_picture/10. More  Community Help/Bag Cleaning.jpg',
    'community|barangay document assistance': r'assets/service_picture/10. More  Community Help/Barangay Document Assistance.jpg',
    'community|bicycle repair': r'assets/service_picture/10. More  Community Help/Bicycle Repair.jpg',
    'community|car washing': r'assets/service_picture/10. More  Community Help/car washing.jpg',
    'community|encoding assistance': r'assets/service_picture/10. More  Community Help/Encoding Assistance.jpg',
    'community|gardening': r'assets/service_picture/10. More  Community Help/Gardening.jpg',
    'community|grass cutting': r'assets/service_picture/10. More  Community Help/Grass Cutting.jpg',
    'community|home inventory assistance': r'assets/service_picture/10. More  Community Help/Home Inventory Assistance.jpg',
    'community|motorcycle washing': r'assets/service_picture/10. More  Community Help/Motorcycle Washing.jpg',
    'community|printing assistance': r'assets/service_picture/10. More  Community Help/Printing Assistance.jpg',
    'community|shoe cleaning': r'assets/service_picture/10. More  Community Help/shoe cleaning.jpg',
    'community|simple sewing repair': r'assets/service_picture/10. More  Community Help/Simple Sewing Repair.jpg',
    'community|tree trimming': r'assets/service_picture/10. More  Community Help/Tree Trimming.jpg',
    'community|uniform repair': r'assets/service_picture/10. More  Community Help/Uniform Repair.jpg',
    'cleaning|apartment cleaning': r'assets/service_picture/2. Cleaning/Apartment Cleaning.jpg',
    'cleaning|bathroom cleaning': r'assets/service_picture/2. Cleaning/Bathroom Cleaning.jpg',
    'cleaning|carpet cleaning': r'assets/service_picture/2. Cleaning/Carpet Cleaning.jpg',
    'cleaning|cleaning': r'assets/service_picture/2. Cleaning/Cleaning.jpg',
    'cleaning|deep cleaning': r'assets/service_picture/2. Cleaning/Deep Cleaning.jpg',
    'cleaning|general decluttering': r'assets/service_picture/2. Cleaning/General Decluttering.jpg',
    'cleaning|house cleaning': r'assets/service_picture/2. Cleaning/House Cleaning.jpg',
    'cleaning|ironing service': r'assets/service_picture/2. Cleaning/Ironing Service.jpg',
    'cleaning|kitchen cleaning': r'assets/service_picture/2. Cleaning/Kitchen Cleaning.jpg',
    'cleaning|laundry assistance': r'assets/service_picture/2. Cleaning/Laundry Assistance.jpg',
    'cleaning|move in cleaning': r'assets/service_picture/2. Cleaning/Move-in Cleaning.jpg',
    'cleaning|move out cleaning': r'assets/service_picture/2. Cleaning/Move-out Cleaning.jpg',
    'cleaning|post construction cleaning': r'assets/service_picture/2. Cleaning/Post-construction Cleaning.jpg',
    'cleaning|upholstery cleaning': r'assets/service_picture/2. Cleaning/Upholstery Cleaning.jpg',
    'cleaning|window cleaning': r'assets/service_picture/2. Cleaning/Window Cleaning.jpg',
    'cleaning|yard cleaning': r'assets/service_picture/2. Cleaning/Yard Cleaning.jpg',
    'repair_technical|aircon cleaning': r'assets/service_picture/3. Repair and Technical Services/Aircon Cleaning.jpg',
    'repair_technical|appliance repair': r'assets/service_picture/3. Repair and Technical Services/Appliance Repair.jpg',
    'repair_technical|basic phone': r'assets/service_picture/3. Repair and Technical Services/Basic Phone.jpg',
    'repair_technical|cctv installation': r'assets/service_picture/3. Repair and Technical Services/CCTV Installation.jpg',
    'repair_technical|computer repair': r'assets/service_picture/3. Repair and Technical Services/Computer Repair.jpg',
    'repair_technical|electric fan repair': r'assets/service_picture/3. Repair and Technical Services/Electric Fan Repair.jpg',
    'repair_technical|electrical repair': r'assets/service_picture/3. Repair and Technical Services/Electrical Repair.jpg',
    'repair_technical|internetwi fi setup': r'assets/service_picture/3. Repair and Technical Services/InternetWi-Fi Setup.jpg',
    'repair_technical|laptop repair': r'assets/service_picture/3. Repair and Technical Services/Laptop Repair.jpg',
    'repair_technical|plumbing repair': r'assets/service_picture/3. Repair and Technical Services/Plumbing Repair.jpg',
    'repair_technical|printer repair': r'assets/service_picture/3. Repair and Technical Services/Printer Repair.jpg',
    'repair_technical|refrigerator repair': r'assets/service_picture/3. Repair and Technical Services/Refrigerator Repair.jpg',
    'repair_technical|repair and technical services': r'assets/service_picture/3. Repair and Technical Services/Repair and Technical Services.jpg',
    'repair_technical|tv repair': r'assets/service_picture/3. Repair and Technical Services/Tv repair.jpg',
    'repair_technical|washing machine repair': r'assets/service_picture/3. Repair and Technical Services/Washing Machine Repair.jpg',
    'handyman|basic painting': r'assets/service_picture/4. Handyman/Basic Painting.jpg',
    'handyman|basic welding assistance': r'assets/service_picture/4. Handyman/Basic Welding Assistance.jpg',
    'handyman|curtain rod installation': r'assets/service_picture/4. Handyman/Curtain Rod Installation.jpg',
    'handyman|door knob replacement': r'assets/service_picture/4. Handyman/Door Knob Replacement.jpg',
    'handyman|drain declogging': r'assets/service_picture/4. Handyman/Drain Declogging.jpg',
    'handyman|furniture assembly': r'assets/service_picture/4. Handyman/Furniture Assembly.jpg',
    'handyman|furniture repair': r'assets/service_picture/4. Handyman/Furniture Repair.jpg',
    'handyman|general household fixes': r'assets/service_picture/4. Handyman/General Household Fixes.jpg',
    'handyman|light fixture installation': r'assets/service_picture/4. Handyman/Light Fixture Installation.jpg',
    'handyman|minor electrical help': r'assets/service_picture/4. Handyman/Minor Electrical Help.jpg',
    'handyman|minor plumbing help': r'assets/service_picture/4. Handyman/Minor Plumbing Help.jpg',
    'handyman|picture frame mounting': r'assets/service_picture/4. Handyman/Picture Frame Mounting.jpg',
    'handyman|shelf installation': r'assets/service_picture/4. Handyman/Shelf Installation.jpg',
    'handyman|wall mounting': r'assets/service_picture/4. Handyman/Wall Mounting.jpg',
    'handyman|water tank cleaning': r'assets/service_picture/4. Handyman/Water Tank Cleaning.jpg',
    'tutoring|art lessons': r'assets/service_picture/5. Tutoring and Lessons/Art Lessons.jpg',
    'tutoring|assignment assistance': r'assets/service_picture/5. Tutoring and Lessons/Assignment Assistance.jpg',
    'tutoring|college subject tutoring': r'assets/service_picture/5. Tutoring and Lessons/College Subject Tutoring.jpg',
    'tutoring|computer basics tutorial': r'assets/service_picture/5. Tutoring and Lessons/Computer Basics Tutorial.jpg',
    'tutoring|elementary tutoring': r'assets/service_picture/5. Tutoring and Lessons/Elementary Tutoring.jpg',
    'tutoring|english tutoring': r'assets/service_picture/5. Tutoring and Lessons/English Tutoring.jpg',
    'tutoring|exam review assistance': r'assets/service_picture/5. Tutoring and Lessons/Exam Review Assistance.jpg',
    'tutoring|high school tutoring': r'assets/service_picture/5. Tutoring and Lessons/High School Tutoring.jpg',
    'tutoring|language tutorial': r'assets/service_picture/5. Tutoring and Lessons/Language Tutorial.jpg',
    'tutoring|math tutoring': r'assets/service_picture/5. Tutoring and Lessons/Math Tutoring.jpg',
    'tutoring|music lessons': r'assets/service_picture/5. Tutoring and Lessons/Music Lessons.jpg',
    'tutoring|online class assistance': r'assets/service_picture/5. Tutoring and Lessons/Online Class Assistance.jpg',
    'tutoring|programming tutorial': r'assets/service_picture/5. Tutoring and Lessons/Programming Tutorial.jpg',
    'tutoring|reading tutorial': r'assets/service_picture/5. Tutoring and Lessons/Reading Tutorial.jpg',
    'tutoring|science tutoring': r'assets/service_picture/5. Tutoring and Lessons/Science Tutoring.jpg',
    'personal_care|babysitting': r'assets/service_picture/6. Personal and Care Services/Babysitting.jpg',
    'personal_care|basic meal preparation': r'assets/service_picture/6. Personal and Care Services/Basic Meal Preparation.jpg',
    'personal_care|document processing assistance': r'assets/service_picture/6. Personal and Care Services/Document Processing Assistance.jpg',
    'personal_care|elderly companion': r'assets/service_picture/6. Personal and Care Services/Elderly Companion.jpg',
    'personal_care|event makeup': r'assets/service_picture/6. Personal and Care Services/Event Makeup.jpg',
    'personal_care|grooming assistance': r'assets/service_picture/6. Personal and Care Services/Grooming Assistance.jpg',
    'personal_care|haircut home service': r'assets/service_picture/6. Personal and Care Services/Haircut Home Service.jpg',
    'personal_care|home organization help': r'assets/service_picture/6. Personal and Care Services/Home Organization Help.jpg',
    'personal_care|home service': r'assets/service_picture/6. Personal and Care Services/Home Service.jpg',
    'personal_care|house sitting': r'assets/service_picture/6. Personal and Care Services/House Sitting.jpg',
    'personal_care|laundry pickup assistance': r'assets/service_picture/6. Personal and Care Services/Laundry Pickup Assistance.jpg',
    'personal_care|manicurepedicure': r'assets/service_picture/6. Personal and Care Services/ManicurePedicure.jpg',
    'personal_care|non medical caregiving': r'assets/service_picture/6. Personal and Care Services/Non-medical Caregiving.jpg',
    'personal_care|personal errand assistance': r'assets/service_picture/6. Personal and Care Services/Personal Errand Assistance.jpg',
    'personal_care|personal shopping assistance': r'assets/service_picture/6. Personal and Care Services/Personal Shopping Assistance.jpg',
    'personal_care|plant care': r'assets/service_picture/6. Personal and Care Services/Plant Care.jpg',
    'moving_errands|appliance transport assistance': r'assets/service_picture/7. Moving and Errands/Appliance Transport Assistance.jpg',
    'moving_errands|delivery assistance': r'assets/service_picture/7. Moving and Errands/Delivery Assistance.jpg',
    'moving_errands|document delivery': r'assets/service_picture/7. Moving and Errands/Document Delivery.jpg',
    'moving_errands|furniture moving': r'assets/service_picture/7. Moving and Errands/Furniture Moving.jpg',
    'moving_errands|general runner service': r'assets/service_picture/7. Moving and Errands/General Runner Service.jpg',
    'moving_errands|grocery pickup': r'assets/service_picture/7. Moving and Errands/Grocery Pickup.jpg',
    'moving_errands|house transfer assistance': r'assets/service_picture/7. Moving and Errands/House Transfer Assistance.jpg',
    'moving_errands|loading and unloading': r'assets/service_picture/7. Moving and Errands/Loading and Unloading.jpg',
    'moving_errands|market errands': r'assets/service_picture/7. Moving and Errands/Market Errands.jpg',
    'moving_errands|medicine pickup': r'assets/service_picture/7. Moving and Errands/Medicine Pickup.jpg',
    'moving_errands|parcel pickup': r'assets/service_picture/7. Moving and Errands/Parcel Pickup.jpg',
    'moving_errands|queue assistance': r'assets/service_picture/7. Moving and Errands/Queue Assistance.jpg',
    'moving_errands|school supply pickup': r'assets/service_picture/7. Moving and Errands/School Supply Pickup.jpg',
    'moving_errands|small item moving': r'assets/service_picture/7. Moving and Errands/Small Item Moving.jpg',
    'moving_errands|water delivery assistance': r'assets/service_picture/7. Moving and Errands/Water Delivery Assistance.jpg',
    'food_event|birthday food preparation': r'assets/service_picture/8. Food and Event Support/Birthday Food Preparation.jpg',
    'food_event|dessert preparation': r'assets/service_picture/8. Food and Event Support/Dessert Preparation.jpg',
    'food_event|dishwashing assistance': r'assets/service_picture/8. Food and Event Support/Dishwashing Assistance.jpg',
    'food_event|event cleanup assistance': r'assets/service_picture/8. Food and Event Support/Event Cleanup Assistance.jpg',
    'food_event|event setup assistance': r'assets/service_picture/8. Food and Event Support/Event Setup Assistance.jpg',
    'food_event|food delivery assistance': r'assets/service_picture/8. Food and Event Support/Food Delivery Assistance.jpg',
    'food_event|home cooking service': r'assets/service_picture/8. Food and Event Support/Home Cooking Service.jpg',
    'food_event|kitchen helper': r'assets/service_picture/8. Food and Event Support/Kitchen Helper.jpg',
    'food_event|packed meal preparation': r'assets/service_picture/8. Food and Event Support/Packed Meal Preparation.jpg',
    'food_event|party decoration assistance': r'assets/service_picture/8. Food and Event Support/Party Decoration Assistance.jpg',
    'food_event|serving assistance': r'assets/service_picture/8. Food and Event Support/Serving Assistance.jpg',
    'food_event|simple event coordination': r'assets/service_picture/8. Food and Event Support/Simple Event Coordination.jpg',
    'food_event|small catering': r'assets/service_picture/8. Food and Event Support/Small Catering.jpg',
    'food_event|snack preparation': r'assets/service_picture/8. Food and Event Support/Snack Preparation.jpg',
    'food_event|table and chair setup': r'assets/service_picture/8. Food and Event Support/Table and Chair Setup.jpg',
    'pet_care|aquarium cleaning': r'assets/service_picture/9. Pet Care/Aquarium Cleaning.jpg',
    'pet_care|basic pet grooming': r'assets/service_picture/9. Pet Care/Basic Pet Grooming.jpg',
    'pet_care|bird cage cleaning': r'assets/service_picture/9. Pet Care/Bird Cage Cleaning.jpg',
    'pet_care|dog walking': r'assets/service_picture/9. Pet Care/Dog Walking.jpg',
    'pet_care|litter cleaning': r'assets/service_picture/9. Pet Care/Litter Cleaning.jpg',
    'pet_care|pet bathing': r'assets/service_picture/9. Pet Care/Pet Bathing.jpg',
    'pet_care|pet exercise assistance': r'assets/service_picture/9. Pet Care/Pet Exercise Assistance.jpg',
    'pet_care|pet feeding': r'assets/service_picture/9. Pet Care/Pet Feeding.jpg',
    'pet_care|pet house cleaning': r'assets/service_picture/9. Pet Care/Pet House Cleaning.jpg',
    'pet_care|pet sitting': r'assets/service_picture/9. Pet Care/Pet Sitting.jpg',
    'pet_care|pet supply pickup': r'assets/service_picture/9. Pet Care/Pet Supply Pickup.jpg',
    'pet_care|pet transport assistance': r'assets/service_picture/9. Pet Care/Pet Transport Assistance.jpg',
    'pet_care|puppy care assistance': r'assets/service_picture/9. Pet Care/Puppy Care Assistance.jpg',
    'pet_care|senior pet assistance': r'assets/service_picture/9. Pet Care/Senior Pet Assistance.jpg',
    'pet_care|vet visit assistance': r'assets/service_picture/9. Pet Care/Vet Visit Assistance.jpg',
  };
}
